---
title: "Bed To Doc"
output: 
 html_document: 
    theme: spacelab
    df_print: paged
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning =FALSE)

library(tidyverse)
library(lubridate)
```

```{r include=FALSE}
encounters <- read_csv("/srv/rsdata/UCSD_F_ED_ENCOUNTERS.csv",
                       col_types = cols(ADT_ARRIVAL_DATE = col_date(format = "%m/%d/%Y"),
                                        ADT_ARRIVAL_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                        ED_DEPARTURE_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                        ED_DISPOSITION_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                        EMERGENCY_ADMISSION_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                        HOSPITAL_ADMISSION_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                        HOSPITAL_DISCHARGE_DATE = col_date(format = "%m/%d/%Y"),
                                        HOSPITAL_DISCHARGE_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                        UPDATE_DATE = col_datetime(format = "%m/%d/%Y %H:%M")))

encounters <- bind_rows(
  encounters %>% filter(ED_OR_UC_DEPARTMENT == 'EMERGENCY'),
  encounters %>% filter(ED_OR_UC_DEPARTMENT == 'Kiswahili') %>% 
    mutate(LANGUAGE = paste(LANGUAGE, ED_OR_UC_DEPARTMENT, sep = '/'),
           ED_OR_UC_DEPARTMENT = BEHAVIORAL_DASHB,
           BEHAVIORAL_DASHB = as.integer(X77)),
  encounters %>% filter(ED_OR_UC_DEPARTMENT == 'English') %>% 
    mutate(FINANCIAL_CLASS_NAME = PATIENT_SEX,
           PATIENT_SEX = LANGUAGE,
           LANGUAGE = ED_OR_UC_DEPARTMENT,
           ED_OR_UC_DEPARTMENT = BEHAVIORAL_DASHB,
           BEHAVIORAL_DASHB = as.integer(X77))
) %>% 
  select(-X77)

useful <- encounters %>% select(PAT_ENC_CSN_ID, ACUITY_LEVEL_C, BEHAVIORAL_DASHB, FIRST_CHIEF_COMPLAINT)

events <- read_delim("/srv/rsdata/UCSD_ED_EVENTS.csv",
                     ";",
                     escape_double = FALSE,
                     col_types = cols(ADT_ARRIVAL_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                      EVENT_TIME = col_datetime(format = "%m/%d/%Y %H:%M")),
                     trim_ws = TRUE)
```

```{r include=FALSE}
filtered <- events %>% 
  inner_join(useful, by = 'PAT_ENC_CSN_ID') %>% 
  filter(EVENT_NAME == "Patient roomed in ED" | EVENT_NAME == "Assign Attending" | EVENT_NAME == 'Patient departed from ED')

bedToDoc <- filtered %>% select(PAT_ENC_CSN_ID, ADT_ARRIVAL_DTTM, EVENT_NAME, EVENT_TIME, ACUITY_LEVEL_C, BEHAVIORAL_DASHB, FIRST_CHIEF_COMPLAINT) %>% 
  unique() %>% 
  group_by(PAT_ENC_CSN_ID,ADT_ARRIVAL_DTTM, EVENT_NAME) %>% 
  mutate(id = row_number()) %>% 
  spread(EVENT_NAME, EVENT_TIME) %>% 
  select(-id) %>% 
  drop_na() %>% 
  rename(id = PAT_ENC_CSN_ID,
         bed = `Patient roomed in ED`,
         doc = `Assign Attending`,
         acuity = ACUITY_LEVEL_C,
         behavioral = BEHAVIORAL_DASHB,
         complaint = FIRST_CHIEF_COMPLAINT,
         depart = `Patient departed from ED`) %>% 
  ungroup() %>% 
  mutate(bedToDoc = as.numeric(doc - bed) / 60,
         docToDepart = as.numeric(depart - doc) / 60,
         date = date(ADT_ARRIVAL_DTTM),
         weekday = wday(ADT_ARRIVAL_DTTM),
         month = month(ADT_ARRIVAL_DTTM),
         year = year(ADT_ARRIVAL_DTTM),
         hour = hour(ADT_ARRIVAL_DTTM),
         acuity = factor(ifelse(acuity %in% c('1','2','3'), 'High Acuity', 'Low Acuity'),
                         levels = c('Low Acuity', 'High Acuity')),
         behavioral = factor(behavioral, labels = c('Non-Behavioral', 'Behavioral'))) %>% 
  select(-ADT_ARRIVAL_DTTM)
```


```{r}
summary <- bedToDoc %>% 
  mutate(category = paste(acuity, behavioral)) %>% 
  group_by(category, hour) %>% 
  summarise(count = n(),
            avg = mean(bedToDoc))

DT::datatable(summary, options=list(autoWidth=TRUE))
```


```{r}
plot <- summary %>% 
  ggplot(aes(x = hour, y = avg, color = category, group = category)) +
  geom_point(aes(size = count), alpha = 0.5) +
  geom_line() +
  scale_x_continuous(breaks = seq(0,23,1)) +
  coord_cartesian(ylim = c(0,100)) +
  theme_bw() +
  labs(x = NULL, y = NULL) +
  ggtitle("Average Time in Ded Waiting for a Physician") +
  theme(legend.position = 'bottom',
        legend.title = element_blank(),
        panel.grid.minor = element_blank()) +
  guides(size = FALSE) +
  scale_color_brewer(palette = 'Dark2')
plot
```

```{r}
summary <- bedToDoc %>% 
  filter(bedToDoc > 0,
         docToDepart > 0) %>% 
  group_by(complaint) %>% 
  summarise(count = n(),
            avg_bd = mean(bedToDoc),
            avg_dd = mean(docToDepart)) %>% 
  ungroup() %>% 
  mutate(ratio = avg_bd / avg_dd) %>% 
  filter(ratio >= 1)
  
```
