---
title: "Patient Census Analysis"
output: 
 html_document: 
    theme: spacelab
    df_print: paged
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE)
library(tidyverse)
library(lubridate)
```

```{r include=FALSE, eval=FALSE}
encounters <- read_csv("/srv/rsdata/UCSD_F_ED_ENCOUNTERS.csv",
                       col_types = cols(ADT_ARRIVAL_DATE = col_date(format = "%m/%d/%Y"),
                                        ADT_ARRIVAL_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                        ED_DEPARTURE_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                        ED_DISPOSITION_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                        EMERGENCY_ADMISSION_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                        HOSPITAL_ADMISSION_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                        HOSPITAL_DISCHARGE_DATE = col_date(format = "%m/%d/%Y"),
                                        HOSPITAL_DISCHARGE_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                        UPDATE_DATE = col_datetime(format = "%m/%d/%Y %H:%M")))

encounters <- bind_rows(
  encounters %>% filter(ED_OR_UC_DEPARTMENT == 'EMERGENCY'),
  encounters %>% filter(ED_OR_UC_DEPARTMENT == 'Kiswahili') %>% 
    mutate(LANGUAGE = paste(LANGUAGE, ED_OR_UC_DEPARTMENT, sep = '/'),
           ED_OR_UC_DEPARTMENT = BEHAVIORAL_DASHB),
  encounters %>% filter(ED_OR_UC_DEPARTMENT == 'English') %>% 
    mutate(FINANCIAL_CLASS_NAME = PATIENT_SEX,
           PATIENT_SEX = LANGUAGE,
           LANGUAGE = ED_OR_UC_DEPARTMENT,
           ED_OR_UC_DEPARTMENT = BEHAVIORAL_DASHB)
)
useful <- encounters %>% select(PAT_ENC_CSN_ID)

```


```{r eval=FALSE}
events <- read_delim("/srv/rsdata/UCSD_ED_EVENTS.csv",
                     ";",
                     escape_double = FALSE,
                     col_types = cols(ADT_ARRIVAL_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                      EVENT_TIME = col_datetime(format = "%m/%d/%Y %H:%M")),
                     trim_ws = TRUE)

arriveDepart <- events %>% 
  inner_join(useful, by = 'PAT_ENC_CSN_ID') %>% 
  filter(
    EVENT_NAME == 'Patient departed from ED'| EVENT_NAME == 'Patient arrived in ED'
  ) %>% select(PAT_ENC_CSN_ID, EVENT_NAME, EVENT_TIME) %>% 
  group_by(PAT_ENC_CSN_ID, EVENT_NAME) %>% 
  mutate(ind = row_number()) %>% 
  spread(EVENT_NAME, EVENT_TIME) %>% 
  select(-ind) %>% 
  rename(arrival = `Patient arrived in ED`,
         depart = `Patient departed from ED`)
```



```{r include=FALSE}
# df <- data.frame(
#   time = seq(from = as.POSIXct('2014-01-02 0', "%Y-%m-%d %H", tz="UTC"), 
#               to = as.POSIXct('2017-12-31 23', "%Y-%m-%d %H", tz="UTC"), 
#               by = 'hour'))
# 
# for(i in 1:nrow(df)){
#   df$count[i] <- sum(arriveDepart$depart > df[i,'time'] & arriveDepart$arrival <= df[i,'time'], na.rm=TRUE)
# }
df <- read_csv('census.csv')
```

```{r include=FALSE}
df <- df %>% 
  mutate(date = date(time),
         hour = factor(hour(time)),
         year = factor(year(time)),
         month = factor(month(time),
                        labels = c('January','February','March','April','May',
                                   'June','July','August','September','October',
                                   'November','December')),
         weekday = factor(wday(time),
                          labels = c('Monday','Tuesday','Wednesday',
                                     'Thursday','Friday','Saturday','Sunday')))
```

```{r fig.height=16, fig.width=8}
p11 <- df %>% group_by(year, hour) %>% 
  ggplot(aes(x = hour, y = count)) +
  geom_boxplot() +
  facet_grid(year~.) +
  theme_bw() +
  ggtitle("Patient Census")
p11
```

```{r fig.height=25, fig.width=8}
p12 <- df %>% group_by(month, hour) %>% 
  ggplot(aes(x = hour, y = count)) +
  geom_boxplot() +
  facet_wrap(~month, ncol=1) +
  theme_bw() +
  ggtitle("Patient Census")
p12
```


```{r fig.height=20, fig.width=8}
p13 <- df %>% group_by(weekday, hour) %>% 
  ggplot(aes(x = hour, y = count)) +
  geom_boxplot() +
  facet_wrap(~weekday, ncol=1) +
  theme_bw() +
  ggtitle("Patient Census")
p13

```
