---
title: "Untitled"
author: "Linping"
date: "5/23/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
library(tidyverse)
library(lubridate)
```

```{r}
Pts123 <- 2.15
Pts45 <- 3.00
serviceLevel <- 0.75
encounters <- read_csv("/srv/rsdata/UCSD_F_ED_ENCOUNTERS.csv",
                       col_types = cols(ADT_ARRIVAL_DATE = col_date(format = "%m/%d/%Y"),
                                        ADT_ARRIVAL_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                        ED_DEPARTURE_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                        ED_DISPOSITION_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                        EMERGENCY_ADMISSION_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                        HOSPITAL_ADMISSION_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                        HOSPITAL_DISCHARGE_DATE = col_date(format = "%m/%d/%Y"),
                                        HOSPITAL_DISCHARGE_DTTM = col_datetime(format = "%m/%d/%Y %H:%M"),
                                        UPDATE_DATE = col_datetime(format = "%m/%d/%Y %H:%M")))

encounters <- bind_rows(
  encounters %>% filter(ED_OR_UC_DEPARTMENT == 'EMERGENCY'),
  encounters %>% filter(ED_OR_UC_DEPARTMENT == 'Kiswahili') %>% 
    mutate(LANGUAGE = paste(LANGUAGE, ED_OR_UC_DEPARTMENT, sep = '/'),
           ED_OR_UC_DEPARTMENT = BEHAVIORAL_DASHB),
  encounters %>% filter(ED_OR_UC_DEPARTMENT == 'English') %>% 
    mutate(FINANCIAL_CLASS_NAME = PATIENT_SEX,
           PATIENT_SEX = LANGUAGE,
           LANGUAGE = ED_OR_UC_DEPARTMENT,
           ED_OR_UC_DEPARTMENT = BEHAVIORAL_DASHB)
)
```

```{r}
data <- encounters %>% 
  mutate(ADT_WEEKDAYS = factor(wday(ADT_ARRIVAL_DATE),
                               levels = c('2', '3', '4', '5', '6', '7', '1'),
                               labels = c('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday')),
         ADT_MONTH = month(ADT_ARRIVAL_DATE),
                           
         ACUITY = factor(ifelse(ACUITY_LEVEL_C %in% c('1','2','3'), 'High', 'Low'),
                         levels = c('Low', 'High')),
         ADT_YEAR = factor(year(ADT_ARRIVAL_DATE)),
         ADT_HOUR = factor(hour(ADT_ARRIVAL_DTTM)),
         SEASON = factor(ifelse(ADT_MONTH %in% c('1', '2', '3'), 'High', 
                                ifelse(ADT_MONTH %in% c('6', '7', '8'), 'Low', 'Medium'))),
         WEEKDAY = factor(ifelse(ADT_WEEKDAYS %in% c('Sunday', 'Monday'), 'Mon/Sun', 'Tue/Sat')))

```

```{r}
PtVolume <- data %>% 
  filter(ADT_ARRIVAL_DATE < as.Date('2017-1-1')) %>% 
  group_by(ADT_ARRIVAL_DATE, ADT_HOUR, ACUITY, SEASON, WEEKDAY) %>% 
  summarise(numPt = n()) %>% 
  ungroup() %>% 
  group_by(ADT_HOUR, ACUITY, SEASON, WEEKDAY) %>% 
  summarise(numPercentile = quantile(numPt, serviceLevel)) %>% 
  ungroup()

# DT::datatable(PtVolume, options = list(autoWidth=TRUE))
```



```{r}
PtEstimate <- PtVolume %>%
  group_by(SEASON, WEEKDAY) %>%
  summarise(EstimateTotal = sum(numPercentile))

# DT::datatable(PtEstimate, options = list(autoWidth=TRUE))

count <- data %>% 
  group_by(ADT_ARRIVAL_DATE, SEASON, WEEKDAY) %>% 
  summarise(n = n())

valid <- count %>% left_join(PtEstimate, by=c("SEASON", "WEEKDAY")) %>% filter(ADT_ARRIVAL_DATE > as.Date('2016-12-31'), ADT_ARRIVAL_DATE < as.Date('2018-01-01'))


valid %>% 
  ggplot(aes(x=ADT_ARRIVAL_DATE))+
  geom_histogram(aes(y=n), stat='identity', na.rm = TRUE) + 
  geom_errorbar(aes(ymax=EstimateTotal, ymin=EstimateTotal),color='red') +
  facet_grid(WEEKDAY~., scales = 'free_x')

valid <- valid %>% mutate(error= n-EstimateTotal,
                          error_sq = error^2)
```

Daily RMSE
```{r}
d_rmse <- sqrt(mean(valid$error_sq))
d_rmse
```

Daily MAE
```{r}
d_mae <- mean(abs(valid$error))
d_mae
```

```{r}
smoothedPtVolume <- PtVolume %>% 
  drop_na() %>% 
  group_by(SEASON, ACUITY, WEEKDAY) %>% 
  mutate(group = rep(1:8, each = 3)) %>% 
  group_by(SEASON, ACUITY, WEEKDAY, group) %>% 
  mutate(smooth = mean(numPercentile)) %>% 
  ungroup()

count <- data %>% 
  group_by(ADT_ARRIVAL_DATE, SEASON, WEEKDAY, ADT_HOUR) %>% 
  summarise(n = n())

valid <- count %>% left_join(smoothedPtVolume, by=c("SEASON", "WEEKDAY", 'ADT_HOUR')) %>% filter(ADT_ARRIVAL_DATE > as.Date('2016-12-31'), ADT_ARRIVAL_DATE < as.Date('2018-01-01'), !is.na(ADT_HOUR))

valid <- valid %>% mutate(error= n-smooth,
                          error_sq = error^2,
                          dttm = ymd_h(paste(ADT_ARRIVAL_DATE, ADT_HOUR)))
```

Hourly RMSE
```{r}
h_rmse <- sqrt(mean(valid$error_sq))
h_rmse
```

Hourly MAE
```{r}
h_mae <- mean(abs(valid$error))
h_mae
```



```{r}
data <- encounters %>% 
  mutate(ADT_WEEKDAYS = factor(wday(ADT_ARRIVAL_DATE),
                               labels = c('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday')),
         ADT_MONTH = factor(month(ADT_ARRIVAL_DATE),
                            labels = c('January','February','March','April','May','June','July','August','September','October','November','December')),
         ACUITY = factor(ifelse(ACUITY_LEVEL_C %in% c('1','2','3'), 'High', 'Low'),
                         levels = c('Low', 'High')),
         ADT_YEAR = factor(year(ADT_ARRIVAL_DATE)),
         ADT_HOUR = factor(hour(ADT_ARRIVAL_DTTM)),
         SEASON = factor(ifelse(ADT_MONTH %in% c('January', 'February', 'March'), 'High', 
                                ifelse(ADT_MONTH %in% c('June', 'July', 'August'), 'Low', 'Medium'))),
         WEEKDAY = factor(ifelse(ADT_WEEKDAYS %in% c('Sunday', 'Monday', 'Tuesday'), 'Sun/Tue', 'Wed/Sat')))
```

```{r}
PtVolume <- data %>% 
  filter(ADT_ARRIVAL_DATE < as.Date('2017-1-1')) %>% 
  group_by(ADT_ARRIVAL_DATE, ADT_HOUR, ACUITY, SEASON, WEEKDAY) %>% 
  summarise(numPt = n()) %>% 
  ungroup() %>% 
  group_by(ADT_HOUR, ACUITY, SEASON, WEEKDAY) %>% 
  summarise(numPercentile = quantile(numPt, serviceLevel)) %>% 
  ungroup()

# DT::datatable(PtVolume, options = list(autoWidth=TRUE))
```



```{r}
PtEstimate <- PtVolume %>%
  group_by(SEASON, WEEKDAY, ACUITY) %>%
  summarise(EstimateTotal = sum(numPercentile))

# DT::datatable(PtEstimate, options = list(autoWidth=TRUE))

count <- data %>% 
  group_by(ADT_ARRIVAL_DATE, SEASON, WEEKDAY, ACUITY) %>% 
  summarise(n = n())

valid <- count %>% left_join(PtEstimate, by=c("SEASON", "WEEKDAY", 'ACUITY')) %>% filter(ADT_ARRIVAL_DATE > as.Date('2016-12-31'), ADT_ARRIVAL_DATE < as.Date('2018-01-01'))


valid %>% 
  ggplot(aes(x=ADT_ARRIVAL_DATE))+
  geom_histogram(aes(y=n, fill = ACUITY), stat='identity', na.rm = TRUE, position = 'dodge') + 
  geom_errorbar(aes(ymax=EstimateTotal, ymin=EstimateTotal, color=ACUITY)) +
  facet_grid(WEEKDAY~ACUITY, scales = 'free_x')

valid <- valid %>% mutate(error= n-EstimateTotal,
                          error_sq = error^2)
```

Daily RMSE
```{r}
d_rmse <- sqrt(mean(valid$error_sq))
d_rmse
```

Daily MAE
```{r}
d_mae <- mean(abs(valid$error))
d_mae
```

```{r}
smoothedPtVolume <- PtVolume %>% 
  drop_na() %>% 
  group_by(SEASON, ACUITY, WEEKDAY) %>% 
  mutate(group = rep(1:8, each = 3)) %>% 
  group_by(SEASON, ACUITY, WEEKDAY, group) %>% 
  mutate(smooth = mean(numPercentile)) %>% 
  ungroup()

count <- data %>% 
  group_by(ADT_ARRIVAL_DATE, SEASON, WEEKDAY, ADT_HOUR) %>% 
  summarise(n = n())

valid <- count %>% left_join(smoothedPtVolume, by=c("SEASON", "WEEKDAY", 'ADT_HOUR')) %>% filter(ADT_ARRIVAL_DATE > as.Date('2016-12-31'), ADT_ARRIVAL_DATE < as.Date('2018-01-01'), !is.na(ADT_HOUR))

valid <- valid %>% mutate(error= n-smooth,
                          error_sq = error^2,
                          dttm = ymd_h(paste(ADT_ARRIVAL_DATE, ADT_HOUR)))
```

Hourly RMSE
```{r}
h_rmse <- sqrt(mean(valid$error_sq))
h_rmse
```

Hourly MAE
```{r}
h_mae <- mean(abs(valid$error))
h_mae
```


